sudo: required
language: clojure

jdk:
  - openjdk8
cache:
  directories:
    - $HOME/.m2
    - $HOME/.cljs
    - node_modules

before_install:
  - curl -O https://download.clojure.org/install/linux-install-1.10.1.536.sh
  - chmod +x linux-install-1.10.1.536.sh
  - sudo ./linux-install-1.10.1.536.sh
  - docker-compose up -d

script:
  - clojure -A:test --reporter kaocha.report/documentation && lein fronttests-once
  
